/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as CategoryTrendsRouteImport } from './routes/category-trends'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as MerchantsIndexRouteImport } from './routes/merchants/index'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions/$transactionId'
import { Route as MerchantsMerchantRouteImport } from './routes/merchants/$merchant'
import { Route as AnalyticsWhatIfRouteImport } from './routes/analytics/what-if'
import { Route as AnalyticsSavingsRateRouteImport } from './routes/analytics/savings-rate'
import { Route as AnalyticsPatternsRouteImport } from './routes/analytics/patterns'
import { Route as AnalyticsInflationRouteImport } from './routes/analytics/inflation'
import { Route as AnalyticsForecastRouteImport } from './routes/analytics/forecast'
import { Route as AnalyticsDiscretionaryRouteImport } from './routes/analytics/discretionary'
import { Route as AnalyticsCashFlowCalendarRouteImport } from './routes/analytics/cash-flow-calendar'
import { Route as ApiGocardlessCallbackRouteImport } from './routes/api/gocardless/callback'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryTrendsRoute = CategoryTrendsRouteImport.update({
  id: '/category-trends',
  path: '/category-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsIndexRoute = MerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MerchantsMerchantRoute = MerchantsMerchantRouteImport.update({
  id: '/merchants/$merchant',
  path: '/merchants/$merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsWhatIfRoute = AnalyticsWhatIfRouteImport.update({
  id: '/analytics/what-if',
  path: '/analytics/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSavingsRateRoute = AnalyticsSavingsRateRouteImport.update({
  id: '/analytics/savings-rate',
  path: '/analytics/savings-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsPatternsRoute = AnalyticsPatternsRouteImport.update({
  id: '/analytics/patterns',
  path: '/analytics/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsInflationRoute = AnalyticsInflationRouteImport.update({
  id: '/analytics/inflation',
  path: '/analytics/inflation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsForecastRoute = AnalyticsForecastRouteImport.update({
  id: '/analytics/forecast',
  path: '/analytics/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsDiscretionaryRoute = AnalyticsDiscretionaryRouteImport.update({
  id: '/analytics/discretionary',
  path: '/analytics/discretionary',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsCashFlowCalendarRoute =
  AnalyticsCashFlowCalendarRouteImport.update({
    id: '/analytics/cash-flow-calendar',
    path: '/analytics/cash-flow-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGocardlessCallbackRoute = ApiGocardlessCallbackRouteImport.update({
  id: '/api/gocardless/callback',
  path: '/api/gocardless/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/category-trends': typeof CategoryTrendsRoute
  '/comparison': typeof ComparisonRoute
  '/logs': typeof LogsRoute
  '/recurring': typeof RecurringRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/triage': typeof TriageRoute
  '/analytics/cash-flow-calendar': typeof AnalyticsCashFlowCalendarRoute
  '/analytics/discretionary': typeof AnalyticsDiscretionaryRoute
  '/analytics/forecast': typeof AnalyticsForecastRoute
  '/analytics/inflation': typeof AnalyticsInflationRoute
  '/analytics/patterns': typeof AnalyticsPatternsRoute
  '/analytics/savings-rate': typeof AnalyticsSavingsRateRoute
  '/analytics/what-if': typeof AnalyticsWhatIfRoute
  '/merchants/$merchant': typeof MerchantsMerchantRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/category-trends': typeof CategoryTrendsRoute
  '/comparison': typeof ComparisonRoute
  '/logs': typeof LogsRoute
  '/recurring': typeof RecurringRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/triage': typeof TriageRoute
  '/analytics/cash-flow-calendar': typeof AnalyticsCashFlowCalendarRoute
  '/analytics/discretionary': typeof AnalyticsDiscretionaryRoute
  '/analytics/forecast': typeof AnalyticsForecastRoute
  '/analytics/inflation': typeof AnalyticsInflationRoute
  '/analytics/patterns': typeof AnalyticsPatternsRoute
  '/analytics/savings-rate': typeof AnalyticsSavingsRateRoute
  '/analytics/what-if': typeof AnalyticsWhatIfRoute
  '/merchants/$merchant': typeof MerchantsMerchantRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/merchants': typeof MerchantsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/category-trends': typeof CategoryTrendsRoute
  '/comparison': typeof ComparisonRoute
  '/logs': typeof LogsRoute
  '/recurring': typeof RecurringRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/triage': typeof TriageRoute
  '/analytics/cash-flow-calendar': typeof AnalyticsCashFlowCalendarRoute
  '/analytics/discretionary': typeof AnalyticsDiscretionaryRoute
  '/analytics/forecast': typeof AnalyticsForecastRoute
  '/analytics/inflation': typeof AnalyticsInflationRoute
  '/analytics/patterns': typeof AnalyticsPatternsRoute
  '/analytics/savings-rate': typeof AnalyticsSavingsRateRoute
  '/analytics/what-if': typeof AnalyticsWhatIfRoute
  '/merchants/$merchant': typeof MerchantsMerchantRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/api/gocardless/callback': typeof ApiGocardlessCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/category-trends'
    | '/comparison'
    | '/logs'
    | '/recurring'
    | '/rules'
    | '/settings'
    | '/triage'
    | '/analytics/cash-flow-calendar'
    | '/analytics/discretionary'
    | '/analytics/forecast'
    | '/analytics/inflation'
    | '/analytics/patterns'
    | '/analytics/savings-rate'
    | '/analytics/what-if'
    | '/merchants/$merchant'
    | '/transactions/$transactionId'
    | '/merchants/'
    | '/transactions/'
    | '/api/gocardless/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/category-trends'
    | '/comparison'
    | '/logs'
    | '/recurring'
    | '/rules'
    | '/settings'
    | '/triage'
    | '/analytics/cash-flow-calendar'
    | '/analytics/discretionary'
    | '/analytics/forecast'
    | '/analytics/inflation'
    | '/analytics/patterns'
    | '/analytics/savings-rate'
    | '/analytics/what-if'
    | '/merchants/$merchant'
    | '/transactions/$transactionId'
    | '/merchants'
    | '/transactions'
    | '/api/gocardless/callback'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/category-trends'
    | '/comparison'
    | '/logs'
    | '/recurring'
    | '/rules'
    | '/settings'
    | '/triage'
    | '/analytics/cash-flow-calendar'
    | '/analytics/discretionary'
    | '/analytics/forecast'
    | '/analytics/inflation'
    | '/analytics/patterns'
    | '/analytics/savings-rate'
    | '/analytics/what-if'
    | '/merchants/$merchant'
    | '/transactions/$transactionId'
    | '/merchants/'
    | '/transactions/'
    | '/api/gocardless/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BudgetsRoute: typeof BudgetsRoute
  CategoriesRoute: typeof CategoriesRoute
  CategoryTrendsRoute: typeof CategoryTrendsRoute
  ComparisonRoute: typeof ComparisonRoute
  LogsRoute: typeof LogsRoute
  RecurringRoute: typeof RecurringRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  TriageRoute: typeof TriageRoute
  AnalyticsCashFlowCalendarRoute: typeof AnalyticsCashFlowCalendarRoute
  AnalyticsDiscretionaryRoute: typeof AnalyticsDiscretionaryRoute
  AnalyticsForecastRoute: typeof AnalyticsForecastRoute
  AnalyticsInflationRoute: typeof AnalyticsInflationRoute
  AnalyticsPatternsRoute: typeof AnalyticsPatternsRoute
  AnalyticsSavingsRateRoute: typeof AnalyticsSavingsRateRoute
  AnalyticsWhatIfRoute: typeof AnalyticsWhatIfRoute
  MerchantsMerchantRoute: typeof MerchantsMerchantRoute
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  MerchantsIndexRoute: typeof MerchantsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  ApiGocardlessCallbackRoute: typeof ApiGocardlessCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-trends': {
      id: '/category-trends'
      path: '/category-trends'
      fullPath: '/category-trends'
      preLoaderRoute: typeof CategoryTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/': {
      id: '/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof MerchantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$merchant': {
      id: '/merchants/$merchant'
      path: '/merchants/$merchant'
      fullPath: '/merchants/$merchant'
      preLoaderRoute: typeof MerchantsMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/what-if': {
      id: '/analytics/what-if'
      path: '/analytics/what-if'
      fullPath: '/analytics/what-if'
      preLoaderRoute: typeof AnalyticsWhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/savings-rate': {
      id: '/analytics/savings-rate'
      path: '/analytics/savings-rate'
      fullPath: '/analytics/savings-rate'
      preLoaderRoute: typeof AnalyticsSavingsRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/patterns': {
      id: '/analytics/patterns'
      path: '/analytics/patterns'
      fullPath: '/analytics/patterns'
      preLoaderRoute: typeof AnalyticsPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/inflation': {
      id: '/analytics/inflation'
      path: '/analytics/inflation'
      fullPath: '/analytics/inflation'
      preLoaderRoute: typeof AnalyticsInflationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/forecast': {
      id: '/analytics/forecast'
      path: '/analytics/forecast'
      fullPath: '/analytics/forecast'
      preLoaderRoute: typeof AnalyticsForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/discretionary': {
      id: '/analytics/discretionary'
      path: '/analytics/discretionary'
      fullPath: '/analytics/discretionary'
      preLoaderRoute: typeof AnalyticsDiscretionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/cash-flow-calendar': {
      id: '/analytics/cash-flow-calendar'
      path: '/analytics/cash-flow-calendar'
      fullPath: '/analytics/cash-flow-calendar'
      preLoaderRoute: typeof AnalyticsCashFlowCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gocardless/callback': {
      id: '/api/gocardless/callback'
      path: '/api/gocardless/callback'
      fullPath: '/api/gocardless/callback'
      preLoaderRoute: typeof ApiGocardlessCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BudgetsRoute: BudgetsRoute,
  CategoriesRoute: CategoriesRoute,
  CategoryTrendsRoute: CategoryTrendsRoute,
  ComparisonRoute: ComparisonRoute,
  LogsRoute: LogsRoute,
  RecurringRoute: RecurringRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  TriageRoute: TriageRoute,
  AnalyticsCashFlowCalendarRoute: AnalyticsCashFlowCalendarRoute,
  AnalyticsDiscretionaryRoute: AnalyticsDiscretionaryRoute,
  AnalyticsForecastRoute: AnalyticsForecastRoute,
  AnalyticsInflationRoute: AnalyticsInflationRoute,
  AnalyticsPatternsRoute: AnalyticsPatternsRoute,
  AnalyticsSavingsRateRoute: AnalyticsSavingsRateRoute,
  AnalyticsWhatIfRoute: AnalyticsWhatIfRoute,
  MerchantsMerchantRoute: MerchantsMerchantRoute,
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  MerchantsIndexRoute: MerchantsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  ApiGocardlessCallbackRoute: ApiGocardlessCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
